more russian fixes
pablohpsilva/vuejs-component-style-guide pull request #31
Opened 2017-03-14 18:11 UTC by uonick

* инлайновые - русизм
* дупликации - что за слово вообще такое?
* запятые
* гуглтранслит
* предложение в форме списка

2017-03-14 18:15 UTC, pablohpsilva commented
Hello @uonick ! :D 
Unfortunately I can't read Russian (yet). Is this PR cool for merging? Maybe @Alex-Sokolov could help you out.

But if it's all OK, just let me know and I shall merge it.

Thank you once again! :)

2017-03-14 18:17 UTC, uonick commented
@pablohpsilva Here only grammatical errors and violations of the rules of language.

2017-03-15 07:20 UTC, Alex-Sokolov requested changes

2017-03-15 07:20 UTC, Alex-Sokolov commented on README-RU.md
> +* Созданые вами атрибуты будет легче понять другим членам команды.
Созданные

2017-03-15 07:20 UTC, Alex-Sokolov commented on README-RU.md
> +* В именованах компонентов лучше использовать только существительные и глаголы, например: `client-api-load`, `drive-upload-success` ([источник](https://github.com/GoogleWebComponents/style-guide#even
В именовании всё-таки, описывается же что в имени стоит указывать

2017-03-15 07:21 UTC, Alex-Sokolov commented
Except two errors looks good! 😄

2017-03-15 07:51 UTC, uonick commented on README-RU.md
> +* В именованах компонентов лучше использовать только существительные и глаголы, например: `client-api-load`, `drive-upload-success` ([источник](https://github.com/GoogleWebComponents/style-guide#even
В `именованах` компонентов

В чем?)

2017-03-15 08:35 UTC, Alex-Sokolov commented on README-RU.md
> +* В именованах компонентов лучше использовать только существительные и глаголы, например: `client-api-load`, `drive-upload-success` ([источник](https://github.com/GoogleWebComponents/style-guide#even
"При именовании компонентов" я бы так сказал

2017-03-16 11:11 UTC, pablohpsilva commented
Great work, guys! You're awesoooome!!!

Can I merge it? :D

2017-03-16 11:38 UTC, uonick commented
@pablohpsilva ,yeah :+1:

2017-03-16 12:37 UTC, merged

2017-03-16 12:37 UTC, pablohpsilva commented
Thank you guys! Great work! :D 
PR accepted.